typography_spectrum: 0.9481548657640815
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.35487750894390047
  lightness: 0.6328902994282544
  saturation: 0.08259013434872031
  rhythmicContrast: 0.10173447174020112
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7231245019938797
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Tegan DeClark
  email: saydotworld@gmail.com
  url: say.world
name: Say.World
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: null
purpose: []
coverPrefs:
  filter: false
