name: Say.World
favicon: null
layout_spectrum: 0.99767
typography_spectrum: 0.73689
title: Explore the universe within reach
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f8fd'
    - '#005f6d'
    - '#bed2d9'
    - '#008b9e'
    - '#00b3cc'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
