name: Say.World
favicon: null
layout_spectrum: 0.2626669080927968
typography_spectrum: 0.08612501248717308
title: Say.world Explore the universe within reach
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0064d6'
    - '#a4cefe'
    - '#000008'
    - '#972800'
    - '#f56e00'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
