name: Say.World
favicon: null
layout_spectrum: 0.7555
typography_spectrum: 0.49492
title: Explore the universe within reach
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0064d6'
    - '#a4cefe'
    - '#000008'
    - '#972800'
    - '#f56e00'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
