name: Say.World
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73689
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f8fd'
    - '#005f6d'
    - '#bed2d9'
    - '#008b9e'
    - '#00b3cc'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
