name: Say.World
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73689
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d4c9b4'
    - '#092948'
    - '#c89a6c'
    - '#67585e'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
